"""Weighted Channel Modules for Allegro Edge Embeddings.

These modules apply learned weights to spherical harmonic edge attributes
to create multi-channel equivariant edge embeddings. They are a key component
of the Allegro architecture's environment embedding.

=== ORIGINAL ALLEGRO (MakeWeightedChannels) ===

Creates weighted edge embeddings from spherical harmonics Y(r_ij).
Input: [n_edges, dim_sh] with multiplicity 1
Output: [n_edges, multiplicity_out, dim_sh]

The weights are generated by the latent MLP and applied per-irrep,
allowing the network to learn which angular momentum channels are
important for each edge.

=== TENN EXTENSION (MakeWeightedChannelsTENN) ===

Extends MakeWeightedChannels to handle 3-channel input for TENN:
- Channel 0: Y(r_ij) - edge direction
- Channel 1: Y(S_i) - center spin direction
- Channel 2: Y(S_j) - neighbor spin direction

Input: [n_edges, 3, dim_sh]
Output: [n_edges, multiplicity_out, dim_sh]

The key difference is the einsum contraction that mixes the 3 input
channels into multiplicity_out output channels, allowing the network
to learn how to combine position and spin information.
"""

from math import ceil

import torch

from e3nn.util.jit import compile_mode


@compile_mode("script")
class MakeWeightedChannels(torch.nn.Module):
    """Apply learned weights to create multi-channel edge embeddings.
    
    This is a core building block of Allegro that transforms single-channel
    spherical harmonic edge attributes into multi-channel embeddings.
    
    === OPERATION ===
    
    For each edge e with spherical harmonics Y_l^m(r_e):
    
    output[e, u, i] = Y[e, i] * weights[e, u, irrep(i)]
    
    where:
    - u: output channel index (1 to multiplicity_out)
    - i: combined (l,m) index over all irreps
    - irrep(i): maps i to which irrep (l-value) it belongs to
    - weights: generated by latent MLP, shape [n_edges, multiplicity_out, n_irreps]
    
    === PURPOSE ===
    
    This allows the network to:
    1. Create multiple "views" of each edge with different weightings
    2. Learn which angular momentum channels are important
    3. Build rich local environment representations
    """
    weight_numel: int
    multiplicity_out: int
    _num_irreps: int

    def __init__(
        self,
        irreps_in,
        multiplicity_out: int,
        pad_to_alignment: int = 1,
    ):
        super().__init__()
        assert all(mul == 1 for mul, ir in irreps_in)
        assert multiplicity_out >= 1
        # Each edgewise output multiplicity is a per-irrep weighted sum over the input
        # So we need to apply the weight for the ith irrep to all DOF in that irrep
        w_index = sum(([i] * ir.dim for i, (mul, ir) in enumerate(irreps_in)), [])
        # pad to padded length
        n_pad = (
            int(ceil(irreps_in.dim / pad_to_alignment)) * pad_to_alignment
            - irreps_in.dim
        )
        # use the last weight, what we use doesn't matter much
        w_index += [w_index[-1]] * n_pad
        self._num_irreps = len(irreps_in)
        self.register_buffer("_w_index", torch.as_tensor(w_index, dtype=torch.long))
        # there is
        self.multiplicity_out = multiplicity_out
        self.weight_numel = len(irreps_in) * multiplicity_out

    def forward(self, edge_attr, weights):
        # weights are [z, u, i]
        # edge_attr are [z, i]
        # i runs over all irreps, which is why the weights need
        # to be indexed in order to go from [num_i] to [i]
        return torch.einsum(
            "zi,zui->zui",
            edge_attr,
            weights.view(
                -1,
                self.multiplicity_out,
                self._num_irreps,
            )[:, :, self._w_index],
        )

    
@compile_mode("script")
class MakeWeightedChannelsTENN(torch.nn.Module):
    """Apply learned weights to 3-channel TENN edge embeddings.
    
    Extension of MakeWeightedChannels for the Time-reversal Equivariant
    Tensor Network (TENN) which uses 3-channel input:
    
    === INPUT STRUCTURE ===
    
    The input has shape [n_edges, 3, dim_sh] where the 3 channels are:
    - v=0: Y(r_ij) - spherical harmonics of edge direction
    - v=1: Y(S_i) - spherical harmonics of center spin direction
    - v=2: Y(S_j) - spherical harmonics of neighbor spin direction
    
    === OPERATION ===
    
    output[e, u, i] = Σ_v edge_attr[e, v, i] * weights[e, v, u, irrep(i)]
    
    This is computed via einsum: "zvi,zvui->zui"
    
    The weights have shape [n_edges, 3, multiplicity_out, n_irreps]:
    - First dimension indexes edge
    - Second dimension (v) indexes the 3 input channels
    - Third dimension (u) indexes output channels
    - Fourth dimension indexes irreps
    
    === PURPOSE ===
    
    This allows TENN to learn how to mix:
    1. Position information (edge direction)
    2. Center spin information
    3. Neighbor spin information
    
    into rich multi-channel embeddings that respect both O(3) and
    time-reversal symmetry.
    
    === KEY DIFFERENCE FROM STANDARD ===
    
    - weight_numel is 3× larger (3 input channels vs 1)
    - Input must have multiplicity 3 (asserted in __init__)
    - Einsum contraction includes the v (channel) index
    """
    weight_numel: int
    multiplicity_out: int
    _num_irreps: int

    def __init__(
        self,
        irreps_in,
        multiplicity_out: int,
        pad_to_alignment: int = 1,
    ):
        """Initialize TENN weighted channels module.
        
        Args:
            irreps_in: Input irreps (must have multiplicity 3 for all irreps)
            multiplicity_out: Number of output channels
            pad_to_alignment: Padding for memory alignment
        """
        super().__init__()
        assert all(mul == 3 for mul, ir in irreps_in)
        assert multiplicity_out >= 1
        # Each edgewise output multiplicity is a per-irrep weighted sum over the input
        # So we need to apply the weight for the ith irrep to all DOF in that irrep
        w_index = sum(([i] * ir.dim for i, (mul, ir) in enumerate(irreps_in)), [])
        # pad to padded length
        n_pad = (
            int(ceil(irreps_in.dim / pad_to_alignment)) * pad_to_alignment
            - irreps_in.dim
        )
        # use the last weight, what we use doesn't matter much
        w_index += [w_index[-1]] * n_pad
        self._num_irreps = len(irreps_in)
        self.register_buffer("_w_index", torch.as_tensor(w_index, dtype=torch.long))
        # there is
        self.multiplicity_out = multiplicity_out
        self.weight_numel = len(irreps_in) * 3 * multiplicity_out

    def forward(self, edge_attr, weights):
        # weights are [z, u, i]
        # edge_attr are [z, i]
        # i runs over all irreps, which is why the weights need
        # to be indexed in order to go from [num_i] to [i]
        return torch.einsum(
            "zvi,zvui->zui",
            edge_attr,
            weights.view(
                -1,
                3,
                self.multiplicity_out,
                self._num_irreps,
            )[:, :, :, self._w_index],
        )
